types = ['german', 'japanese', 'vegetarian', 'french', 'african', 'american', 'barbecue', 'czech', 'chinese', 'thai',
         'mexican', 'indian', 'cafe', 'pizza', 'italian']

restaurant_data = [
    ['german', "Hans' Bavarian Eatery", '3', '4', '45 Bavarian St.'],
    ['japanese', 'Sushi Garden', '5', '5', '123 Sushi Lane'],
    ['vegetarian', 'Green Delight', '4', '3', '78 Veggie Blvd'],
    ['french', 'Le Petit Bistro', '4', '5', '10 French Ave'],
    ['african', 'Savanna Soul', '3', '4', '22 Savannah Way'],
    ['american', 'Joe’s Diner', '4', '3', '15 Main St'],
    ['barbecue', 'BBQ Heaven', '5', '5', '89 Grill Rd'],
    ['czech', 'Bohemian Hall', '4', '4', '456 Central Park'],
    ['chinese', 'Peking Duck House', '3', '4', '34 China Town'],
    ['thai', 'Bangkok Spices', '4', '4', '50 Thai St'],
    ['mexican', 'El Pueblo', '5', '5', '99 Fiesta Ave'],
    ['indian', 'Tandoori Palace', '4', '5', '14 Spice Rd'],
    ['cafe', 'Bean Town', '3', '4', '67 Coffee Ave'],
    ['pizza', 'Pizza Palace', '4', '5', '123 Pizza St'],
    ['italian', 'Mamma Mia', '5', '4', '234 Pasta Blvd'],
    ['german', 'Bavarian Lodge', '3', '3', '23 Alpine Rd'],
    ['japanese', 'Ninja Sushi', '4', '5', '45 Shogun Ave'],
    ['vegetarian', 'Healthy Bites', '4', '4', '12 Leafy St'],
    ['french', 'Café de Paris', '3', '5', '30 Paris St'],
    ['african', 'Kilimanjaro Kitchen', '5', '5', '70 Serengeti Ave'],
    ['american', 'Burger Barn', '4', '4', '89 Burger Blvd'],
    ['barbecue', 'Smoky Trails', '3', '4', '15 Smoke Rd'],
    ['czech', 'Prague Pub', '4', '3', '55 Castle Hill'],
    ['chinese', 'Dim Sum House', '4', '4', '80 Bamboo Lane'],
    ['thai', 'Thai Orchid', '5', '5', '66 Orchid St'],
    ['mexican', 'Taco Fiesta', '3', '4', '28 Cinco de Mayo'],
    ['indian', 'Curry Corner', '4', '5', '101 Spice St'],
    ['cafe', 'Morning Brew', '3', '4', '22 Coffee Rd'],
    ['pizza', 'Cheesy Bites', '4', '5', '77 Pepperoni Ave'],
    ['italian', 'The Pasta Place', '5', '4', '34 Italy Rd'],
    ['german', 'Berlin Bistro', '4', '4', '88 Brandenburg St'],
    ['japanese', 'Sakura Blossoms', '4', '5', '102 Blossom Ave'],
    ['vegetarian', 'Veggie Delight', '3', '3', '56 Green Rd'],
    ['french', 'La Belle Vie', '5', '5', '99 Eiffel Blvd'],
    ['african', 'Safari Feast', '4', '4', '50 Savannah Lane'],
    ['american', 'Liberty Diner', '4', '3', '17 Freedom Rd'],
    ['barbecue', 'Rib Rack', '5', '5', '120 BBQ Blvd'],
    ['czech', 'Czech House', '3', '4', '77 Praha St'],
    ['chinese', 'Great Wall Cuisine', '4', '4', '88 Beijing Rd'],
    ['thai', 'Thai Garden', '5', '5', '44 Lotus Ave'],
    ['mexican', 'Cantina', '4', '5', '33 Sombrero St'],
    ['indian', 'Masala Magic', '3', '4', '21 Curry Lane'],
    ['cafe', 'Java Junction', '4', '4', '55 Brew Blvd'],
    ['pizza', 'Slice of Life', '5', '5', '100 Pepperoni Blvd'],
    ['italian', 'Little Italy', '4', '4', '70 Piazza Ave']
]
